### ISSUE TITLE
Unattended mode needs interaction if you have multiple subscriptions in Azure

### ISSUE THREAD

**Issue by dako365** [tmaestrini/easyGovernance#58]
When it comes to authentication with Connect-AzAccount you have to choose your Azure subscription.
Thats a problem when you want to use easyG in an unattended mode because it needs an interaction.

**Comment by tmaestrini** [comment]
I suggest to bring in an additional (not mandatory) parameter where you could specify (or let's say "reference") an existing Azure subscription.
@dako365 would this help to resolve the problem?

**Comment by dako365** [comment]
yeah would be awesome. please choose the Subscription ID as parameter

**Comment by tmaestrini** [comment]
@dako365 Done. Please test it. 

You can either specify…
1.  the `AzureSubscriptionId` parameter when running `Start-Validation` or 
2. set the `$azureSubscriptionId` parameter when initializing `Set-UnattendedRun` 

Thanks for feedback! :)

**Comment by dako365** [comment]
Hi @tmaestrini 

I tried it, but unfortunately  there is an error regarding the $AzureSubscriptionID variable. When calling Start-Validation an error message " [Connect-Tenant] failed: A parameter cannot be found that matches parameter name 'AzureSubscriptionId'." pops up. 
We need to check. Didn't find the bug so far.

**Comment by tmaestrini** [comment]
@dako365 I've pushed some changes on this branch. Please check them if the fit as prerequisite for #59 and provide feedback before we merge into develop. Thank you.

**Comment by tmaestrini** [comment]
@dako365 Could you please adjust the documentation (README.md) when you're good with all the changes?

**Comment by tmaestrini** [comment]
@dako365 Any progress on this?

**Comment by dako365** [comment]
Hey easyT @tmaestrini ! I still have some problems with MFA. Need to test it with a global admin without any CA policies. Will prioritize this and will give you some feedback on saturday (not sure which saturday 🦖 )

**Comment by dako365** [comment]
Still does not work as expected in my environment. Is your test successfull?

User is excluded from every CA policy

2026-01-22 17:15:48 ERROR   [Connect-Tenant] failed: Connect-TenantAzure > Authentication failed against resource GraphEndpointResourceId. User interaction is required. This may be due to the conditional access policy settings such as multi-factor authentication (MFA). Please rerun 'Connect-AzAccount' with additional parameter '-AuthScope GraphEndpointResourceId'.
2026-01-22 17:15:48 ERROR   [Start-Validation] Terminating routine due to erronous connection attempt.

**Comment by tmaestrini** [comment]
I will dig into this an will let you know.
